### ISSUE TITLE
Shaircast installation error 

### ISSUE THREAD

**Issue by Floki73** [nguyer/shaircast#4]
What's wrong? I always get this error message when installing SHAIRCAST:
.....
make: Entering directory '/root/shaircast/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
dns_sd_bindings.target.mk:137: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: **\* [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/root/shaircast/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.1.13+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/shaircast/node_modules/mdns
gyp ERR! node -v v0.10.41
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
shaircast@0.0.1 /root/shaircast
├── debug@2.2.0  extraneous
├── forge@2.3.0  extraneous
├── httplike@1.0.1  extraneous
├── ip@0.3.2  extraneous
├── metricstream@0.0.0  extraneous
├── node-forge@0.6.38  extraneous
├── portastic@0.0.1  extraneous
├── priorityqueuejs@0.2.0  extraneous
├── random-mac@0.0.4  extraneous
├── randomstring@1.0.3  extraneous
└─┬ speaker@0.2.6
  ├─┬ debug@2.2.0
  │ └── ms@0.7.1
  └─┬ readable-stream@1.0.33
    ├── core-util-is@1.0.2
    ├── inherits@2.0.1
    ├── isarray@0.0.1
    └── string_decoder@0.10.31

**Comment by nguyer** [comment]
Looks like you are missing the header file `dns_sd.h`. If you're trying this on a Raspberry Pi, on Raspbian, install the appropriate dev package and then try again.
`$ sudo apt-get install libavahi-compat-libdnssd-dev`

**Comment by nguyer** [comment]
@Floki73 I'm going to go ahead and close this issue since it's been a while. Please feel free to re-open if it's still an issue.
